name: Generate Contribution Snake

on:
  schedule:
    - cron: "0 */6 * * *" # every 6 hours
  workflow_dispatch:     # allows manual run

permissions:
  contents: write        # important so the action can push files

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate contribution snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: KAOS-CODM
          outputs: github-contribution-grid-snake.svg

      - name: Commit generated SVG to output branch
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: github-actions@github.com
          message: "chore: update contribution snake"
          add: "github-contribution-grid-snake.svg"
          branch: output
